- name: Create frontend src directory
  become: yes
  ansible.builtin.file:
    path: "{{ frontend_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: "copy files"
  become: yes
  synchronize:
    src: ../frontend/
    dest: ~/{{ frontend_dir }}/
    rsync_opts:
        - --exclude=node_modules/*

- name: Copy Docker Compose file to remote hosts
  become: yes
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ frontend_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Build image and with build args
  become: yes
  community.docker.docker_image:
    name: "{{frontend_service_name}}"
    build:
      path: "/home/ubuntu/{{ frontend_dir }}"
      dockerfile: Dockerfile.prod
    source: build
    

- name: Deploy stack from a compose file
  become: yes
  community.docker.docker_stack:
    state: present
    name: "{{frontend_stack_name}}"
    compose:
      - "{{ frontend_dir }}/docker-compose.yaml"
  when: "'master' in group_names"
