# - name: Bind Address
#   become: yes
#   shell: |
#     curl -X PUT http://{{ couchdb_user }}:{{ couchdb_pass }}@127.0.0.1:5984/_node/_local/_config/chttpd/bind_address -d '"0.0.0.0"'


- name: Enable Cluster
  become: yes
  shell: |
    curl -X POST -H "Content-Type: application/json" http://{{ couchdb_user }}:{{ couchdb_pass }}@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "{{ couchdb_user }}", "password":"{{ couchdb_pass }}", "node_count":"3"}'

- name: Set Worker Container Names
  become: yes
  register: command_output
  shell: |
    docker ps | grep "couchdb:latest" | awk '{ print $15 }'
  # docker ps --format {% raw %}"{{.Names}}"{% endraw %} 
  when: "'workers' in group_names"

- name: Store Container Names
  ansible.builtin.set_fact:
    docker_container_names: '{{ command_output.stdout }}'
  when: "'workers' in group_names"

- name: Print Container Names
  ansible.builtin.debug:
    var: docker_container_names
  when: "'workers' in group_names"
