- name: Openstack Server Setup
  tags: local
  hosts: localhost
  vars_files:
    - variables/openstack-vars.yaml
  gather_facts: true
  roles:
    - role: openstack-common
    - role: openstack-volumes
    - role: openstack-security-group
    - role: openstack-instances    

- name: Swarm Host Common Setup
  tags: swarm
  hosts: master:workers
  gather_facts: false
  roles:
    - role: host-common
    - role: host-volumes
    - role: docker-common

- name: Swarm Master Node Setup
  tags: swarm
  hosts: master
  gather_facts: false
  roles:
    - role: swarm-master

- name: Swarm Workers Node Setup
  tags: swarm
  hosts: workers
  gather_facts: false
  roles:
    - role: swarm-workers

- name: Create overlay network
  tags: swarm
  hosts: master
  vars_files:
    - variables/docker-vars.yaml
  tasks:
    - name: Create an overlay network
      become: yes
      docker_network:
        name: "{{ overlay_network_name }}"
        driver: "overlay"
        attachable: true
        scope: "swarm"

- name: CouchDB Docker Common Setup
  tags: couchdb
  hosts: master:workers
  vars_files:
    - variables/couchdb-vars.yaml
    - variables/docker-vars.yaml
  gather_facts: false
  roles:
    - role: couchdb-common

- name: CouchDB Stack Deploy
  tags: couchdb
  hosts: master
  vars_files:
    - variables/couchdb-vars.yaml
  gather_facts: false
  roles:
    - role: couchdb-stack-deploy

- name: CouchDB Cluster Setup
  tags: couchdb
  hosts: workers:master
  vars_files:
    - variables/couchdb-vars.yaml
  gather_facts: false
  roles:
    - role: couchdb-cluster-setup

- name: CouchDB Cluster Join
  tags: couchdb
  hosts: master
  vars_files:
    - variables/couchdb-vars.yaml
  gather_facts: false
  roles:
    - role: couchdb-cluster-join

- name: React Frontend Deploy
  tags: frontend
  hosts: master:workers
  vars_files:
    - variables/frontend-vars.yaml
    - variables/docker-vars.yaml
  gather_facts: false
  roles:
    - role: react-frontend-deploy

- name: Harvester Deploy
  tags: harvester
  hosts: master:workers
  vars_files:
    - variables/docker-vars.yaml
    - variables/couchdb-vars.yaml
    - variables/harvester-vars.yaml
  gather_facts: false
  roles:
    - role: harvester-deploy

- name: Backend Deploy
  tags: backend
  hosts: master:workers
  vars_files:
    - variables/docker-vars.yaml
    - variables/couchdb-vars.yaml
    - variables/backend-vars.yaml
  gather_facts: false
  roles:
    - role: gin-backend-deploy