# Create a security group
- name: Create a security group
  openstack.cloud.security_group:
    name: '{{item.name }}'
    description: '{{item.description }}'
    state: present
  loop: '{{cidr_security_groups }}'

- name: Create a list of security group names
  ansible.builtin.set_fact:
    sg_names: '{{ sg_names | default([])+ [ item.name ] }}'
  loop: '{{ cidr_security_groups }}'

- name: Create a security group
  openstack.cloud.security_group:
    name: '{{item.name }}'
    description: '{{item.description }}'
    state: present
  loop: '{{group_security_groups }}'

- name: Create a list of security group names
  ansible.builtin.set_fact:
    sg_names: '{{ sg_names | default([])+ [ item.name ] }}'
  loop: '{{ group_security_groups }}'

- ansible.builtin.debug:
    msg: "Security group(s) {{sg_names}} have been created."

# Create securit group rules
- name: Create CIDR based security group rules.
  openstack.cloud.security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ cidr_security_groups }}'

- name: Create group based security group rules.
  openstack.cloud.security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{item.port_range_max }}'
    remote_group: '{{ item.remote_group }}'
    state: present
  loop: '{{ group_security_groups }}'