- name: Gather facts
  ansible.builtin.setup:
    filter:
      - 'ansible_distribution'
      - 'ansible_distribution_release'

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ["apt-transport-https", "build-essential", "ca-certificates", "curl", "software-properties-common", "gnupg","git", "python3-dev", "python3-setuptools", "python3-pip", "vim", "erlang"]
    allow_unauthenticated: true
    update_cache: yes

- name: Update pip
  become: yes
  ansible.builtin.pip:
    name: ["pip", "jsondiff"]
    state: latest
