- name: Create CouchDB directory
  become: yes
  ansible.builtin.file:
    path: "{{ couchdb_dir }}/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Copy Docker Compose file to remote hosts
  become: yes
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ couchdb_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy DB config file to remote hosts
  become: yes
  ansible.builtin.template:
    src: couchdb_config.ini.j2
    dest: "{{ couchdb_dir }}/config/couchdb_config.ini"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"