- name: Init a new swarm
  become: yes
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
  register: docker_swarm_re

- ansible.builtin.debug:
    msg: "{{docker_swarm_re}}"

- name: Store Worker Join Token
  ansible.builtin.set_fact:
    worker_join_token: "{{ docker_swarm_re.swarm_facts.JoinTokens.Worker }}"

- name: Store Manager Join Token
  ansible.builtin.set_fact:
    manager_join_token: "{{ docker_swarm_re.swarm_facts.JoinTokens.Manager }}"

- name: Store Manager IP Address
  ansible.builtin.set_fact:
    manager_addr: "{{ ansible_host }}"

# - name: Get info on Docker Swarm
#   become: yes
#   community.docker.docker_swarm_info:
#   ignore_errors: true
#   register: result

# - name: Inform about basic flags
#   become: yes
#   ansible.builtin.debug:
#     msg: |
#       Was able to talk to docker daemon: {{ result.can_talk_to_docker }}
#       Docker in Swarm mode: {{ result.docker_swarm_active }}
#       This is a Manager node: {{ result.docker_swarm_manager }}