FROM python:3.9 
COPY . ./

ENV MASTODON_SERVER={{mastodon_server}}
ENV MASTODON_TOKEN={{mastodon_token}}
ENV DB_USER={{couchdb_user}}
ENV DB_PASSWORD={{couchdb_pass}}

RUN pip install -r "requirements.txt"
CMD ["python", "./main.py"] 
